apiVersion: v1
kind: Service
metadata:
  name: todo-back-service
spec:
  selector:
    app: todo-app # Selects the pods to expose through the service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080 # Port exposed by the service
      targetPort: 8080 # Port exposed by the pod
      nodePort: 30000 # Makes the service accessible from outside the cluster via this port
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
