server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${database_name}
    username: ${username}
    password: ${password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update