services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - 5432:5432
    volumes:
      - todo:/var/lib/postgresql/data
  app:
    image: todo-app:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      database_name: todo
      database_hostname: postgres
      database_port: 5432
      username: postgres
      password: postgres
    depends_on:
      - postgres

volumes:
    todo: